[project]
name = "day5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yuvarajgowda02", email = "yuvarajsit26@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "docx>=0.2.4",
    "groq>=1.6.0",
    "pydantic>=2.13.4",
    "pypdf>=6.16.2",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
day5 = "day5:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
